# Generated by Django 3.2 on 2023-05-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.category')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
