# Generated by Django 3.0.1 on 2023-06-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20230607_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='coupon_used',
            field=models.BooleanField(default=False),
        ),
    ]
